Repository hypothesis/h-assets, pull requests merged in 2021-07, with the labels that each got.

#2 Remove most type hints
  src/h_assets/assets.py
Labels: tech debt

#3 Fill out the introduction in the README
  README.md
Labels: Backend

#5 Split up view and environment
  src/h_assets/__init__.py
  src/h_assets/environment.py
  src/h_assets/view.py
  tests/unit/h_assets/environment_test.py
  tests/unit/h_assets/view_test.py
Labels: tech debt

#6 Add product metadata to the `pyproject.toml` file
  .cookiecutter.json
  pyproject.toml
Labels: enhancement
